name = "HN_V2"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Fontconfig = "186bb1d3-e1f7-5a2c-a377-96d770f13627"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
DrWatson = "2.19.0"
julia = "1.11.6"
